fix: Docker build fails
edgexfoundry-holding/device-usb-camera pull request #6
Opened 2022-01-27 14:23 UTC by FelixTing

- Add required alpine packages to build-stage.
- For the module name and docker image tag, rename "IOTechSystems" and "iotechsystems" to "edgexfoundry".

fix: #4 

Signed-off-by: Felix Ting <felix@iotechsys.com>

2022-01-27 14:57 UTC, cloudxxx8 requested changes
build the image from `alpine:3.15`

2022-01-27 14:57 UTC, cloudxxx8 commented on go.mod
>  go 1.16
use go 1.17

2022-01-27 14:57 UTC, cloudxxx8 commented on Dockerfile
use golang:1.17-alpine3.15

2022-01-27 15:56 UTC, FelixTing commented on go.mod
>  go 1.16
modified

2022-01-27 15:56 UTC, FelixTing commented on Dockerfile
modified

2022-01-28 09:46 UTC, cloudxxx8 approved these changes
LGTM

2022-01-28 09:46 UTC, merged